/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yzyffmpegplayer_PlayUtil */

#ifndef _Included_com_example_yzyffmpegplayer_PlayUtil
#define _Included_com_example_yzyffmpegplayer_PlayUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yzyffmpegplayer_PlayUtil
 * Method:    play_native
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_example_yzyffmpegplayer_PlayUtil_play_1native
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
